---
title: "Covid-19 Testing Progress"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(DT)
library(plotly)

today <- read.csv("./testnumbers/2020-03-12.csv")
all <- read.csv('./testnumbers/all.csv')

```


Introduction {.sidebar}
-------------------------------------

This website aims to track the numbers of SARC-CoV-2 tests performed across the United States. The data is obtained daily from the websites of state health departments which report that information.

```{r}
# shiny inputs defined here
```

Row
-----------------------------------------------------------------------

### States or territories reporting

```{r}
valueBox(32, icon = "fa-flag-usa")
```

### Tests per million residents

```{r}
valueBox(23, icon = "fa-vials")
```

### Growth in the number of tests compared to the previous day

```{r}
valueBox("59%", 
         icon = "fa-chart-line",
         color = "warning")
```

### Share of positives

```{r}
valueBox("20%", 
         icon = "fa-chart-line",
         color = "warning")
```

Row  {.tabset data-height=1400}
-----------------------------------------------------------------------

### March 12

```{r}

covid <- all %>%
  filter(date == "2020-03-12")

covid %>%
  select(state, total, delta, tests_per_million, pct_positive, positive, negative, pending) %>%
  datatable(options = list(dom = 't', pageLength = 50, style = 'bootstrap'), colnames = c('State', 'Total tests', '+ tests since March 11', 'Tests per million', '% positive', '+', '-', 'Pending'), rownames = FALSE) %>%
  formatRound('tests_per_million', 2) %>%
  formatPercentage('pct_positive', 2) %>%
  formatPercentage('delta', 2)


```

### March 11

```{r}

covid <- all %>%
  filter(date == "2020-03-11")

covid %>%
  select(state, total, delta, tests_per_million, pct_positive, positive, negative, pending) %>%
  datatable(options = list(dom = 't', pageLength = 50, style = 'bootstrap'), colnames = c('State', 'Total tests', '+ tests since March 9', 'Tests per million', '% positive', '+', '-', 'Pending'), rownames = FALSE) %>%
  formatRound('tests_per_million', 2) %>%
  formatPercentage('pct_positive', 2) %>%
  formatPercentage('delta', 2)


```

### March 9

```{r}

covid <- all %>%
  filter(date == "2020-03-09")

covid %>%
  select(state, total, delta, tests_per_million, pct_positive, positive, negative, pending) %>%
  datatable(options = list(dom = 't', pageLength = 50, style = 'bootstrap'), colnames = c('State', 'Total tests', '+ tests since March 8', 'Tests per million', '% positive', '+', '-', 'Pending'), rownames = FALSE) %>%
  formatRound('tests_per_million', 2) %>%
  formatPercentage('pct_positive', 2) %>%
  formatPercentage('delta', 2)


```

### March 8

```{r}

covid <- all %>%
  filter(date == "2020-03-08")

covid %>%
  select(state, total, delta, tests_per_million, pct_positive, positive, negative, pending) %>%
  datatable(options = list(dom = 't', pageLength = 50, style = 'bootstrap'), colnames = c('State', 'Total tests', '+ tests since March 6', 'Tests per million', '% positive', '+', '-', 'Pending'), rownames = FALSE) %>%
  formatRound('tests_per_million', 2) %>%
  formatPercentage('pct_positive', 2) %>%
  formatPercentage('delta', 2)


```

### March 6

```{r}

covid <- all %>%
  filter(date == "2020-03-06")

covid %>%
  select(state, total, delta, tests_per_million, pct_positive, positive, negative, pending) %>%
  datatable(options = list(dom = 't', pageLength = 50, style = 'bootstrap'), colnames = c('State', 'Total tests', '+ tests since March 5', 'Tests per million', '% positive', '+', '-', 'Pending'), rownames = FALSE) %>%
  formatRound('tests_per_million', 2) %>%
  formatPercentage('pct_positive', 2) %>%
  formatPercentage('delta', 2)


```

### March 5

```{r}


covid <- all %>%
  filter(date == "2020-03-05")

covid %>%
  select(state, total, tests_per_million, pct_positive, positive, negative, pending) %>%
  datatable(options = list(dom = 't', pageLength = 50, style = 'bootstrap'), colnames = c('State', 'Total tests', 'Tests per million', '% positive', '+', '-', 'Pending'), rownames = FALSE) %>%
  formatRound('tests_per_million', 2) %>%
  formatPercentage('pct_positive', 2)

```

Row
-----------------------------------------------------------------------

### Tests per million residents

```{r}

today$code <- state.abb[match(today$state, state.name)]

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

today$rounded <- round(today$tests_per_million, digits = 0)


map <- plot_geo(today, locationmode = 'USA-states')
map <- map %>% add_trace(
  z = ~rounded, text = NULL, locations = ~code,
  color = ~tests_per_million, colors = 'Reds'
) 

map <- map %>% colorbar(title = "Tests per million")

map <- map %>% layout(
  geo = g
)

map


```



Row
-----------------------------------------------------------------------

### Number of tests

```{r}
totals <- all %>%
  filter(state == 'Total')

fig <- plot_ly(
  x = totals$date,
  y = totals$total,
  name = "Testing totals",
  type = 'bar'
)

fig

```


### Day-on-day growth in testing

```{r}
totals <- all %>%
  filter(state == 'Total')

fig <- plot_ly(
  x = totals$date,
  y = totals$delta,
  name = "Testing totals",
  type = 'bar'
) %>%
  layout(yaxis = list(tickformat = "%"))

fig

```

